/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131313',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-bright': '#3a3939',
        'surface-dim': '#131313',
        surface: '#131313',
        'surface-variant': '#353534',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c6d0',
        primary: '#adc6ff',
        'primary-container': '#385283',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary': '#122f5f',
        'on-primary-container': '#ecf0ff',
        'on-primary-fixed': '#001a42',
        secondary: '#bdc6df',
        'secondary-container': '#3e475b',
        'on-secondary': '#273044',
        tertiary: '#ffdea4',
        'tertiary-container': '#6c4d01',
        'on-tertiary': '#412d00',
        'on-tertiary-container': '#ffede6',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#8e909a',
        'outline-variant': '#44474f',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#455e90',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Space Grotesk', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        '4xl': '1.5rem',
      },
    },
  },
  plugins: [],
};